travis:
  secure:
    BINSTAR_TOKEN: 3IrgkEGD+/jAb2LiVKPmdUR8RCaHJhJxHgZ4kiTJrLdTJg7ik36naIAtY1AJugjPmJThRV5KQSBANPQ7yUa/u/Ln+UdnwLdi3ULXoYlDYyuk0GWscQ1I9CzOlGKfAP189MXsvLIHBAMO/jlsG6v/wauZ0HZBl1a04mjJBaa3PgOKGWXUUD+yOaI/w+M2jvSrUIbwDSP9WT94T1Rcsh1oCnsllJQ+HEKqQJEbOJfj4OzPKMd8r6/R9Tt4YrBn7QpVktqglrUhvnc4774ZZaIGsFEt2E/IbQaqDAY8yG986xcE2H9Xnok1APSR7oT54M4VuQQk5Row890cZTlqIReR0qNGl6daTAKFfyukAoqjv4nw6nXT8XhRAc1AmVpDlpIg8nXepLo1SUdPnjbRIDuwmhgDqCFHZ4KDpTxMCtkDtmRVrDfN5yjE0X8WP0F966PAjty2bBXWi8agjS/WIZWUlHsFvUc5kFH8iMmm3qR9l2Ds6oTvcElkMHsOoOX61TZ+SYPllnGc6gLd6rkpknbFAsxWjCYNLAeEjrvXumWWZvynSTx2sR0dlE+ig6KE1emtBad+xol7mUEksCp10qeGhnqIii+glvs+9TdNclPF45f2H0NXSZE0pOQ3u71LIphkY83rN5Sso2S/dm4G5N4eDRhTMfGwcl4/AsbYSJDrANA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
