travis:
  secure:
    BINSTAR_TOKEN: Hpm1rbNz1WF2MziTn6BOrf2WETKy8Wuf5dh0lTpVEGl7Gm1p5u9U2Y0jvyXtb5n5OK49OF5g27q51ejklk6q/80qg2mszCSb+smZ8dlKUgc99T+ATyr28WPrthwSLrdnhsfV59oGvOVJ/SB0CBd3H+VoiiL7WJv+Brmfkisho6oDJELj0F9Pt+MOVbsJ4tG4Do3zVxjLG8/lApBlivUVtImRucO3BiSkg8DpMkdOyoE6bBcOKr0stE7MF/DbuFrI0nRQfETZW77i3X1QMFqog5mQn0Olfl1dBCwFzXLq5xxDMGFGxihVh/pHNIjR4PWKQaFbJGmtHTxN7SCsUiT8EnvRAlpuumh8LjAVmHYqYzTd8o0EmyDogP2nR41SgK6IGNgp2URqwvAe6Xf6y9naC34BsfmLzZ3bVrBKsUcABarfObLBt7PBN9DOyO9SDGG1UxeilrHul6NtVE0FQGUk0pVsN6pMNB5kEdo6T+czrfESU3p/jroFR7YufZvqn7ELAv/rKax1oMq+bs/lFLApnstlOl+jyf55XInIGe58aZlMXzBeEIp9ez+HByz3sKYx81svlE1WS+cUvyEd4nBgT185muCpmpd+wTOlEFDho8n932/lL6U0Rx23m4jZIXgK+ZZHGsBcn81mB63BRpMKBpeDKUFuiDdjelhb1zodAxA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
